// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQG2_e8FYE0d8WicPRc-I1K-gV0raC0g',
    appId: '1:231676087477:web:329230758c7ad7863042fc',
    messagingSenderId: '231676087477',
    projectId: 'fit-track-9709a',
    authDomain: 'fit-track-9709a.firebaseapp.com',
    storageBucket: 'fit-track-9709a.appspot.com',
    measurementId: 'G-FJVRXB7N78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrupj9v_3UgUk1Xg1OvEcEUN9YVq5cP0',
    appId: '1:231676087477:android:d8ca67eabdd1109c3042fc',
    messagingSenderId: '231676087477',
    projectId: 'fit-track-9709a',
    storageBucket: 'fit-track-9709a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAucz8n-BSa8KrU8_WVWenoyPCLHU4ti4',
    appId: '1:231676087477:ios:d841c9056bd194f93042fc',
    messagingSenderId: '231676087477',
    projectId: 'fit-track-9709a',
    storageBucket: 'fit-track-9709a.appspot.com',
    iosClientId: '231676087477-0hcisvjcqc1ue66vc2ci4cvk2kdnel6b.apps.googleusercontent.com',
    iosBundleId: 'com.senacelik.fitTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAucz8n-BSa8KrU8_WVWenoyPCLHU4ti4',
    appId: '1:231676087477:ios:d841c9056bd194f93042fc',
    messagingSenderId: '231676087477',
    projectId: 'fit-track-9709a',
    storageBucket: 'fit-track-9709a.appspot.com',
    iosClientId: '231676087477-0hcisvjcqc1ue66vc2ci4cvk2kdnel6b.apps.googleusercontent.com',
    iosBundleId: 'com.senacelik.fitTrack',
  );
}
